import * as z from "zod";

import {
  apiErrorSchema,
  cursorPageInfoSchema,
  healthResponseSchema,
  platformRequestHeadersSchema,
  requestContextHeadersSchema,
  tenantRequestHeadersSchema,
  validationErrorSchema,
} from "./http.ts";
import {
  authLoginRequestSchema,
  authLogoutResponseSchema,
  authSessionSchema,
  authUserSchema,
  updateUserPreferencesSchema,
} from "./auth.ts";
import {
  platformSessionSchema,
  platformUserSchema,
  provisionPlatformUserSchema,
} from "./platform.ts";
import {
  brandSchema,
  businessUnitSchema,
  createBrandSchema,
  createOutletSchema,
  createTenantSchema,
  locationSchema,
  organizationSnapshotSchema,
  outletSchema,
  tenantSchema,
  updateBrandSchema,
  updateOutletSchema,
  updateTenantSchema,
  workspaceSchema,
  workspaceStructureSchema,
} from "./organization.ts";
import {
  catalogCategorySchema,
  catalogModifierGroupSchema,
  catalogModifierOptionSchema,
  catalogOutletProductItemSchema,
  catalogOutletProductSchema,
  catalogOutletSnapshotSchema,
  catalogProductImageSchema,
  catalogProductModifierGroupSchema,
  catalogProductSchema,
  catalogProductVariantSchema,
  catalogSnapshotSchema,
  createCatalogCategorySchema,
  createCatalogModifierGroupSchema,
  createCatalogModifierOptionSchema,
  createCatalogOutletProductForOutletSchema,
  createCatalogOutletProductSchema,
  createCatalogProductImageSchema,
  createCatalogProductModifierGroupSchema,
  createCatalogProductSchema,
  createCatalogProductVariantSchema,
  updateCatalogCategorySchema,
  updateCatalogModifierGroupSchema,
  updateCatalogModifierOptionSchema,
  updateCatalogOutletProductSchema,
  updateCatalogProductImageSchema,
  updateCatalogProductModifierGroupSchema,
  updateCatalogProductSchema,
  updateCatalogProductVariantSchema,
} from "./catalog.ts";
import {
  entitlementSnapshotSchema,
  moduleEntitlementSchema,
  platformEntitlementParamsSchema,
  platformSetTenantEntitlementSchema,
  platformTenantMasterSchema,
  replaceSubscriptionSchema,
  setTenantEntitlementSchema,
  subscriptionSchema,
} from "./entitlement.ts";
import {
  authorizationContextSchema,
  createMembershipSchema,
  createRoleSchema,
  membershipSchema,
  roleSchema,
  updateMembershipSchema,
  updateRoleSchema,
  workspaceContextSchema,
  workspaceOutletSchema,
} from "./access.ts";
import {
  integrationBindingSchema,
  moduleBoundaryRuleSchema,
  moduleEventHandlerRegistrationSchema,
  moduleInstallStepSchema,
  moduleInstallationSchema,
  moduleManifestSchema,
  moduleNavigationRegistrationSchema,
  moduleRouteRegistrationSchema,
  moduleSettingRegistrationSchema,
  moduleInstallationListSchema,
  workspaceNavigationSchema,
  integrationBindingListSchema,
  pauseIntegrationBindingSchema,
} from "./module-manifest.ts";
import {
  effectiveLimitSchema,
  limitErrorDetailsSchema,
  packageVersionSnapshotSchema,
  usageAdjustmentSchema,
  usageCounterSchema,
  usageEventSchema,
  subscriptionOverviewSchema,
  usageSummarySchema,
} from "./packages-limits.ts";
import {
  commandContextSchema,
  domainEventEnvelopeSchema,
  inboxConsumerReceiptSchema,
} from "./events.ts";
import { supportAccessGrantSchema } from "./support-access.ts";
import { publicQrResolutionSchema, tableQrTokenRecordSchema } from "./table-qr.ts";
import {
  closeRegisterSessionSchema,
  currentRegisterSessionSchema,
  openRegisterSessionSchema,
  recordCashMovementSchema,
  registerSessionSchema,
} from "./pos-shift.ts";
import { sellableMenuSchema } from "./menu.ts";
import {
  cancelOrderSchema,
  createPosOrderSchema,
  orderSchema,
  posOrderListSchema,
} from "./orders.ts";
import {
  checkoutSchema,
  payOrderSchema,
  receiptSchema,
  refundOrderSchema,
  saleRefundsSchema,
} from "./billing.ts";
import {
  heldCartListSchema,
  heldCartSchema,
  holdCartSchema,
  resumedCartSchema,
} from "./held-carts.ts";
import {
  activateDeviceSchema,
  deviceActivationTicketSchema,
  deviceListSchema,
  deviceSchema,
  registerDeviceSchema,
} from "./devices.ts";
import { memberListSchema, sessionRevocationSchema } from "./access.ts";
import { fileUploadRequestSchema, fileUploadTicketSchema } from "./files.ts";
import {
  acceptInvitationSchema,
  createInvitationSchema,
  invitationAcceptedSchema,
  invitationListSchema,
  invitationPreviewSchema,
  invitationSchema,
  invitationTokenRequestSchema,
} from "./invitations.ts";

export type ContractSchema = z.ZodType;

export function toOpenApiSchema(schema: ContractSchema) {
  return z.toJSONSchema(schema, { target: "openapi-3.0" });
}

export const commonOpenApiSchemas = {
  ApiError: toOpenApiSchema(apiErrorSchema),
  AuthLoginRequest: toOpenApiSchema(authLoginRequestSchema),
  AuthLogoutResponse: toOpenApiSchema(authLogoutResponseSchema),
  AuthSession: toOpenApiSchema(authSessionSchema),
  AuthUser: toOpenApiSchema(authUserSchema),
  UpdateUserPreferences: toOpenApiSchema(updateUserPreferencesSchema),
  AuthorizationContext: toOpenApiSchema(authorizationContextSchema),
  Brand: toOpenApiSchema(brandSchema),
  CatalogCategory: toOpenApiSchema(catalogCategorySchema),
  CatalogModifierGroup: toOpenApiSchema(catalogModifierGroupSchema),
  CatalogModifierOption: toOpenApiSchema(catalogModifierOptionSchema),
  CatalogOutletProduct: toOpenApiSchema(catalogOutletProductSchema),
  CatalogOutletProductItem: toOpenApiSchema(catalogOutletProductItemSchema),
  CatalogOutletSnapshot: toOpenApiSchema(catalogOutletSnapshotSchema),
  CatalogProduct: toOpenApiSchema(catalogProductSchema),
  CatalogProductImage: toOpenApiSchema(catalogProductImageSchema),
  CatalogProductModifierGroup: toOpenApiSchema(catalogProductModifierGroupSchema),
  CatalogProductVariant: toOpenApiSchema(catalogProductVariantSchema),
  CatalogSnapshot: toOpenApiSchema(catalogSnapshotSchema),
  CreateBrand: toOpenApiSchema(createBrandSchema),
  CreateCatalogCategory: toOpenApiSchema(createCatalogCategorySchema),
  CreateCatalogModifierGroup: toOpenApiSchema(createCatalogModifierGroupSchema),
  CreateCatalogModifierOption: toOpenApiSchema(createCatalogModifierOptionSchema),
  CreateCatalogOutletProduct: toOpenApiSchema(createCatalogOutletProductSchema),
  CreateCatalogOutletProductForOutlet: toOpenApiSchema(createCatalogOutletProductForOutletSchema),
  CreateCatalogProduct: toOpenApiSchema(createCatalogProductSchema),
  CreateCatalogProductImage: toOpenApiSchema(createCatalogProductImageSchema),
  CreateCatalogProductModifierGroup: toOpenApiSchema(createCatalogProductModifierGroupSchema),
  CreateCatalogProductVariant: toOpenApiSchema(createCatalogProductVariantSchema),
  CreateMembership: toOpenApiSchema(createMembershipSchema),
  CreateRole: toOpenApiSchema(createRoleSchema),
  CreateOutlet: toOpenApiSchema(createOutletSchema),
  CreateTenant: toOpenApiSchema(createTenantSchema),
  CursorPageInfo: toOpenApiSchema(cursorPageInfoSchema),
  HealthResponse: toOpenApiSchema(healthResponseSchema),
  Membership: toOpenApiSchema(membershipSchema),
  EntitlementSnapshot: toOpenApiSchema(entitlementSnapshotSchema),
  ModuleEventHandlerRegistration: toOpenApiSchema(moduleEventHandlerRegistrationSchema),
  ModuleInstallStep: toOpenApiSchema(moduleInstallStepSchema),
  ModuleInstallation: toOpenApiSchema(moduleInstallationSchema),
  ActivateDevice: toOpenApiSchema(activateDeviceSchema),
  Device: toOpenApiSchema(deviceSchema),
  DeviceActivationTicket: toOpenApiSchema(deviceActivationTicketSchema),
  DeviceList: toOpenApiSchema(deviceListSchema),
  RegisterDevice: toOpenApiSchema(registerDeviceSchema),
  FileUploadRequest: toOpenApiSchema(fileUploadRequestSchema),
  FileUploadTicket: toOpenApiSchema(fileUploadTicketSchema),
  AcceptInvitation: toOpenApiSchema(acceptInvitationSchema),
  CreateInvitation: toOpenApiSchema(createInvitationSchema),
  Invitation: toOpenApiSchema(invitationSchema),
  InvitationAccepted: toOpenApiSchema(invitationAcceptedSchema),
  InvitationList: toOpenApiSchema(invitationListSchema),
  InvitationPreview: toOpenApiSchema(invitationPreviewSchema),
  InvitationTokenRequest: toOpenApiSchema(invitationTokenRequestSchema),
  MemberList: toOpenApiSchema(memberListSchema),
  ModuleInstallationList: toOpenApiSchema(moduleInstallationListSchema),
  SessionRevocation: toOpenApiSchema(sessionRevocationSchema),
  WorkspaceNavigation: toOpenApiSchema(workspaceNavigationSchema),
  ModuleEntitlement: toOpenApiSchema(moduleEntitlementSchema),
  IntegrationBinding: toOpenApiSchema(integrationBindingSchema),
  IntegrationBindingList: toOpenApiSchema(integrationBindingListSchema),
  PauseIntegrationBinding: toOpenApiSchema(pauseIntegrationBindingSchema),
  ModuleManifest: toOpenApiSchema(moduleManifestSchema),
  ModuleNavigationRegistration: toOpenApiSchema(moduleNavigationRegistrationSchema),
  ModuleRouteRegistration: toOpenApiSchema(moduleRouteRegistrationSchema),
  ModuleSettingRegistration: toOpenApiSchema(moduleSettingRegistrationSchema),
  DomainEventEnvelope: toOpenApiSchema(domainEventEnvelopeSchema),
  CommandContext: toOpenApiSchema(commandContextSchema),
  SupportAccessGrant: toOpenApiSchema(supportAccessGrantSchema),
  PublicQrResolution: toOpenApiSchema(publicQrResolutionSchema),
  TableQrTokenRecord: toOpenApiSchema(tableQrTokenRecordSchema),
  ModuleBoundaryRule: toOpenApiSchema(moduleBoundaryRuleSchema),
  InboxConsumerReceipt: toOpenApiSchema(inboxConsumerReceiptSchema),
  EffectiveLimit: toOpenApiSchema(effectiveLimitSchema),
  LimitErrorDetails: toOpenApiSchema(limitErrorDetailsSchema),
  OrganizationSnapshot: toOpenApiSchema(organizationSnapshotSchema),
  BusinessUnit: toOpenApiSchema(businessUnitSchema),
  Location: toOpenApiSchema(locationSchema),
  Outlet: toOpenApiSchema(outletSchema),
  PlatformEntitlementParams: toOpenApiSchema(platformEntitlementParamsSchema),
  PlatformRequestHeaders: toOpenApiSchema(platformRequestHeadersSchema),
  PlatformSession: toOpenApiSchema(platformSessionSchema),
  PlatformSetTenantEntitlement: toOpenApiSchema(platformSetTenantEntitlementSchema),
  PlatformTenantMaster: toOpenApiSchema(platformTenantMasterSchema),
  PlatformUser: toOpenApiSchema(platformUserSchema),
  PackageVersionSnapshot: toOpenApiSchema(packageVersionSnapshotSchema),
  ProvisionPlatformUser: toOpenApiSchema(provisionPlatformUserSchema),
  RequestContextHeaders: toOpenApiSchema(requestContextHeadersSchema),
  ReplaceSubscription: toOpenApiSchema(replaceSubscriptionSchema),
  Role: toOpenApiSchema(roleSchema),
  TenantRequestHeaders: toOpenApiSchema(tenantRequestHeadersSchema),
  WorkspaceContext: toOpenApiSchema(workspaceContextSchema),
  WorkspaceOutlet: toOpenApiSchema(workspaceOutletSchema),
  Workspace: toOpenApiSchema(workspaceSchema),
  WorkspaceStructure: toOpenApiSchema(workspaceStructureSchema),
  Tenant: toOpenApiSchema(tenantSchema),
  SetTenantEntitlement: toOpenApiSchema(setTenantEntitlementSchema),
  Subscription: toOpenApiSchema(subscriptionSchema),
  UpdateBrand: toOpenApiSchema(updateBrandSchema),
  UpdateCatalogCategory: toOpenApiSchema(updateCatalogCategorySchema),
  UpdateCatalogModifierGroup: toOpenApiSchema(updateCatalogModifierGroupSchema),
  UpdateCatalogModifierOption: toOpenApiSchema(updateCatalogModifierOptionSchema),
  UpdateCatalogOutletProduct: toOpenApiSchema(updateCatalogOutletProductSchema),
  UpdateCatalogProduct: toOpenApiSchema(updateCatalogProductSchema),
  UpdateCatalogProductImage: toOpenApiSchema(updateCatalogProductImageSchema),
  UpdateCatalogProductModifierGroup: toOpenApiSchema(updateCatalogProductModifierGroupSchema),
  UpdateCatalogProductVariant: toOpenApiSchema(updateCatalogProductVariantSchema),
  UpdateMembership: toOpenApiSchema(updateMembershipSchema),
  UpdateRole: toOpenApiSchema(updateRoleSchema),
  UpdateOutlet: toOpenApiSchema(updateOutletSchema),
  UpdateTenant: toOpenApiSchema(updateTenantSchema),
  UsageAdjustment: toOpenApiSchema(usageAdjustmentSchema),
  UsageCounter: toOpenApiSchema(usageCounterSchema),
  UsageEvent: toOpenApiSchema(usageEventSchema),
  SubscriptionOverview: toOpenApiSchema(subscriptionOverviewSchema),
  UsageSummary: toOpenApiSchema(usageSummarySchema),
  ValidationError: toOpenApiSchema(validationErrorSchema),
} as const;

export const posOpenApiSchemas = {
  HeldCart: toOpenApiSchema(heldCartSchema),
  HeldCartList: toOpenApiSchema(heldCartListSchema),
  HoldCart: toOpenApiSchema(holdCartSchema),
  ResumedCart: toOpenApiSchema(resumedCartSchema),
  RefundOrder: toOpenApiSchema(refundOrderSchema),
  SaleRefunds: toOpenApiSchema(saleRefundsSchema),
  Receipt: toOpenApiSchema(receiptSchema),
  CancelOrder: toOpenApiSchema(cancelOrderSchema),
  PosOrderList: toOpenApiSchema(posOrderListSchema),
  Checkout: toOpenApiSchema(checkoutSchema),
  PayOrder: toOpenApiSchema(payOrderSchema),
  CreatePosOrder: toOpenApiSchema(createPosOrderSchema),
  Order: toOpenApiSchema(orderSchema),
  CloseRegisterSession: toOpenApiSchema(closeRegisterSessionSchema),
  CurrentRegisterSession: toOpenApiSchema(currentRegisterSessionSchema),
  OpenRegisterSession: toOpenApiSchema(openRegisterSessionSchema),
  RecordCashMovement: toOpenApiSchema(recordCashMovementSchema),
  RegisterSession: toOpenApiSchema(registerSessionSchema),
  SellableMenu: toOpenApiSchema(sellableMenuSchema),
} as const;
